server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable_accounts_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51SmATKHaZ1dlBO07zRLFRZjnwoikA3GDMtH4DmNEp5DTaCGzKvOPCS8EvN14BkehD42LdyuiMdDML5JLuiVUxQAm00rJFwjFHQ
  webhook:
    secret: whsec_585864cb52b602aab5b185c56da172a9396a4adc7da9586534330220e6598203

client:
  url: http://localhost:3000
