spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/HarshilChampaneri/lovable-clone-config-server
      username: HarshilChampaneri
      password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      default-label: main

server.port: 8888